// Options.idl : IDL source for Options.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Options.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
	
interface ITTObject;
[
    object,
    uuid(F763D0E1-6359-11d3-B24E-000000000000),
    pointer_default(unique),
    local
]

interface ITTObject: IUnknown
{
	HRESULT InitObject();
	HRESULT Activate([in]int nState);
	HRESULT GetState([out, retval]int* pnState);
	HRESULT GetByID([in]int nID, [in, out]VARIANT** ppVar);
	HRESULT PutByID([in]int nID, [in] VARIANT* pVar);
	HRESULT GetByName([in]BSTR strName, [in, out]VARIANT** ppVar);
	HRESULT PutByName([in]BSTR strName, [in]VARIANT* pVar);
}

[
	object,
	uuid(A2A4F837-24CC-4CA8-B36F-ACF7D040D101),
	dual,
	helpstring("ITTOptions Interface"),
	pointer_default(unique)
]
interface ITTOptions : IDispatch
{
};

[
	uuid(024401C5-443E-4C48-8782-0C25FCD3AD24),
	version(1.0),
	helpstring("Options 1.0 Type Library")
]
library OPTIONSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(492E31D4-B80D-11D3-AF24-00A0CC23E698),
		helpstring("TTOptions Class")
	]
	coclass TTOptions
	{
		[default] interface ITTOptions;
		interface ITTObject;
	};
};
