// Options.idl : IDL source for Options.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Options.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
	

	[
		object,
		uuid(A2A4F837-24CC-4CA8-B36F-ACF7D040D101),
		dual,
		helpstring("ITTOptions Interface"),
		pointer_default(unique)
	]
	interface ITTOptions : IDispatch
	{
	};

[
	uuid(024401C5-443E-4C48-8782-0C25FCD3AD24),
	version(1.0),
	helpstring("Options 1.0 Type Library")
]
library OPTIONSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(492E31D4-B80D-11D3-AF24-00A0CC23E698),
		helpstring("TTOptions Class")
	]
	coclass TTOptions
	{
		[default] interface ITTOptions;
	};
};
